# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages
dist: trusty
r_github_packages: mnpopcenter/ipumsr/ipumsexamples

r:
- release
- oldrel
- devel
- 3.2

before_install:
    - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
    - sudo apt-get --yes --force-yes update -qq
    - sudo apt-get install --yes libproj-dev libgeos-dev libgdal-dev libudunits2-dev
    - Rscript -e 'if(R.version$major == "3" && substr(R.version$minor, 1, 1) == "2") install.packages("jsonlite")'

after_success:
  - Rscript -e 'covr::codecov()'

env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
