# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages
dist: trusty
r_github_packages: mnpopcenter/ipumsr/ipumsexamples

matrix:
  include:
    - r: release
      env: cache_type=v1
    - r: oldrel
      env: cache_type=v1
    - r: devel
      env: cache_type=v3
    - r: 3.2
      env: cache_type=v2

before_install:
    - test $TRAVIS_R_VERSION_STRING = "devel" && Rscript -e 'install.packages("devtools")'
    - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
    - sudo apt-get --yes --force-yes update -qq
    - sudo apt-get install --yes libproj-dev libgeos-dev libgdal-dev libudunits2-dev
    - test $TRAVIS_R_VERSION_STRING = "3.2" && Rscript -e 'install.packages("jsonlite")'

after_success:
  - test $TRAVIS_R_VERSION_STRING = "release" && Rscript -e 'covr::codecov()'

env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
